// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQeJUjXn_FXnExAIXpyxzhjg8aExUT73s',
    appId: '1:878913938614:android:6ae7dd649b28787346b217',
    messagingSenderId: '878913938614',
    projectId: 'pickeep-3341c',
    storageBucket: 'pickeep-3341c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy4Tcb-E11lgBBZJmYvxxDxeEyJfoICjQ',
    appId: '1:878913938614:ios:dd9f1ce35e2f35ab46b217',
    messagingSenderId: '878913938614',
    projectId: 'pickeep-3341c',
    storageBucket: 'pickeep-3341c.appspot.com',
    iosClientId: '878913938614-vtlv20et0dnm3afjffo7us8vtfra5kp1.apps.googleusercontent.com',
    iosBundleId: 'com.technion.pickeep',
  );
}
